root: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: './tsconfig.json'
  ecmaFeatures:
    jsx: true
extends:
  - airbnb-typescript
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier/@typescript-eslint'
  - 'prettier/react'
plugins:
  - jest
  - react-native
  - prettier
rules:
  no-use-before-define: off
  react/jsx-props-no-spreading: off
  '@typescript-eslint/no-use-before-define': off
  react/jsx-curly-newline: off
  import/no-extraneous-dependencies:
    [
      'error',
      {
        'devDependencies':
          [
            '**/*.test.ts',
            '**/*.test.tsx',
            '**/*.stories.ts',
            '**/*.stories.tsx',
            'test-*.js',
            'jest.config.js',
          ],
      },
    ]
env:
  react-native/react-native: true
  jest/globals: true
