root: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: './tsconfig.json'
  ecmaFeatures:
    jsx: true
extends:
  - airbnb-typescript
  - prettier
plugins:
  - jest
  - react-native
rules:
  no-use-before-define: off
  '@typescript-eslint/no-use-before-define': off
  react/jsx-curly-newline: off
  import/no-extraneous-dependencies:
    [
      'error',
      {
        'devDependencies': ['**/*.test.ts', '**/*.test.tsx', '**/*.stories.ts', '**/*.stories.tsx'],
      },
    ]
env:
  react-native/react-native: true
  jest/globals: true
